lib/customer_feedback_web/router.ex
defmodule CustomerFeedbackWeb.Router do
  use CustomerFeedbackWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CustomerFeedbackWeb do
    pipe_through :browser

    get "/signup", LoginController, :signup
    post "/signup", LoginController, :create_account
  end

  # new code
  pipeline :auth do
    plug Auth.Pipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug :put_user_token
  end

  defp put_user_token(conn, _) do
    user = Guardian.Plug.current_resource(conn)
    conn = Plug.Conn.assign(conn, :current_user, user)
  end

  # Maybe logged in routes
  scope "/", CustomerFeedbackWeb do
    pipe_through [:browser, :auth]

    get "/", LoginController, :index

    post "/", LoginController, :authenticate_account

    # get "/login", SessionController, :new
    # post "/login", SessionController, :login
    # post "/logout", SessionController, :logout
  end

  # Definitely logged in scope
  scope "/", CustomerFeedbackWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/secret", LoginController, :secret
    get "/profile", ProfileController, :index
    get "/edit", ProfileController, :edit
    put "/edit", ProfileController, :update_profile

    resources "/questions", QuestionController
    # resources "/ratings", RatingController

    get "/ratings", RatingController, :mobile_form
    post "/ratings", RatingController, :check_mobile

    post "/ratings/new", RatingController, :create_customer
    put "/ratings/edit/:id", RatingController, :update_customer

    get "/ratings/:id/new/:mobile", RatingController, :new
    post "/ratings/:id/new/:mobile", RatingController, :create
  end
end

lib/customer_feedback_web/controllers/login_controller.ex
defmodule CustomerFeedbackWeb.LoginController do
  use CustomerFeedbackWeb, :controller

  alias CustomerFeedback.Accounts.Account
  alias CustomerFeedback.Accounts

  alias Auth.Guardian

  def index(conn, _params) do
    maybe_user = Guardian.Plug.current_resource(conn)

    if maybe_user do
      redirect(conn, to: "/secret")
    else
      render(conn, "index.html")
      # redirect(conn, to: "/login")
    end
  end

  def secret(conn, _params) do
    render(conn, "secret.html")
  end

  def authenticate_account(conn, %{"username" => username, "password" => password}) do
    case Accounts.authenticate_account(username, password) do
      {:ok, record} ->
        conn
        |> Guardian.Plug.sign_in(record)
        |> IO.inspect()
        |> redirect(to: "/secret")

      false ->
        IO.inspect("error occured")
        render(conn, "index.html", error: "invalid username or password")

        # |> redirect(to: batch_path(conn, :index))

        # {:error, %Ecto.Changeset{} = changeset} ->
        # render(conn, "index.html", changeset: changeset)
    end
  end

  def signup(conn, _params) do
    changeset = Accounts.change_account(%Account{})
    render(conn, "signup.html", changeset: changeset)
  end

  def create_account(conn, %{"account" => account_params}) do
    case Accounts.create_account(account_params) do
      {:ok, account} ->
        conn
        |> put_flash(:info, "Account created successfully.")
        |> Guardian.Plug.sign_in(account)
        |> IO.inspect()
        |> redirect(to: "/secret")

      # |> redirect(to: Routes.account_path(conn, :show, account))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "signup.html", changeset: changeset)
    end
  end
end

lib/customer_feedback_web/views/login_view.ex
defmodule CustomerFeedbackWeb.LoginView do
  use CustomerFeedbackWeb, :view
end

lib/customer_feedback_web/templates/login/index.html.eex
<div class="min-h-screen flex flex-col justify-center" style="background:linear-gradient(rgba(38, 174, 239, 0.75), rgba(38, 174, 239, 0.75)), url(<%= Routes.static_path(@conn, "/images/home.jpg") %>);background-size: cover;background-repeat: no-repeat;background-position: center;">

  <div class="flex-auto"></div>

  <div class="mx-auto text-white mb-12">
    <div style="font-size: 3em;"><strong>Customer</strong> Feedback</div>
    <div class="text-right text-lg text-green-lightest border-t border-white pt-1 italic"></div>
  </div>

  <div class="bg-white rounded shadow-lg p-4 max-w-xs mx-auto" style="width: 100%;">
    <div class="text-lg text-grey-dark mb-8 pb-2 border-b border-grey-lighter">Login</div>
      <%= form_for @conn, Routes.login_path(@conn, :authenticate_account), fn f -> %>

        <div class="mb-4">
          <%= label f, :username, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= text_input f, :username, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-6">
          <%= label f, :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= password_input f, :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "******************" %>

        </div>

        <div class="flex items-center justify-between">
          <%= submit "Sign In", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
          <%# <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
            Forgot Password?
          </a> %>
          <%= button "Sign Up", to: "/signup", method: "get", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
          
        </div>

      <% end %>
  </div>

  <div class="flex-auto"></div>
  <div class="max-w-xl mx-auto px-4 py-8 flex items-center justify-center text-white text-sm">
    <span>@2019</span>
  </div>
</div>

lib/customer_feedback_web/templates/login/secret.html.eex
<h1>Secret Page</h1>
<div>Username: <%= @current_user.name %></div>

lib/customer_feedback_web/templates/login/signup.html.eex
<div class="min-h-screen flex flex-col justify-center" style="background:linear-gradient(rgba(38, 174, 239, 0.75), rgba(38, 174, 239, 0.75)), url(<%= Routes.static_path(@conn, "/images/home.jpg") %>);background-size: cover;background-repeat: no-repeat;background-position: center;">

  <div class="flex-auto"></div>

  <div class="mx-auto text-white mb-12">
    <div style="font-size: 3em;"><strong>Customer</strong> Feedback</div>
    <div class="text-right text-lg text-green-lightest border-t border-white pt-1 italic"></div>
  </div>

  <div class="bg-white rounded shadow-lg p-4 max-w-xs mx-auto" style="width: 100%;">
    <div class="text-lg text-grey-dark mb-8 pb-2 border-b border-grey-lighter">Signup</div>
      <%= form_for @changeset, Routes.login_path(@conn, :create_account), fn f -> %>
        
        <div class="mb-4">
          <%= label f, :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= text_input f, :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>


        <div class="mb-4">
          <%= label f, :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= text_input f, :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-4">
          <%= label f, :phone, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= text_input f, :phone, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>


        <div class="mb-4">
          <%= label f, :user_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= text_input f, :user_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>

        <div class="mb-6">
          <%= label f, :password, class: "block text-gray-700 text-sm font-bold mb-2" %>
          <%= password_input f, :password, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline", placeholder: "******************" %>

        </div>

        <div class="flex items-center justify-between">
          <%= submit "Signup", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>

          <%= button "Login", to: "/", method: "get", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>

      <% end %>
  </div>

  <div class="flex-auto"></div>
  <div class="max-w-xl mx-auto px-4 py-8 flex items-center justify-center text-white text-sm">
    <span>@2019</span>
  </div>
</div>